# Symétries
### Louis Noirot, mars 2025
###### LMAPR1492

In [2]:
import numpy as np
import itertools
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from pymatgen.symmetry.bandstructure import HighSymmKpath

def latex_fix(label):
    replace = {
        "\Gamma": "Γ",
    }
    if label in replace:
        label = replace[label]
    return label

# Plotting of the Brillouin zone
def go_points(points, size=4, color="black", labels=None):
    mode = "markers" if labels is None else "markers+text"

    if labels is not None:
        for il in range(len(labels)):
            labels[il] = latex_fix(labels[il])

    import plotly.graph_objects as go
    return go.Scatter3d(
        x=[v[0] for v in points],
        y=[v[1] for v in points],
        z=[v[2] for v in points],
        marker=dict(size=size, color=color),
        mode=mode,
        text=labels,
        textfont_color=color,
        showlegend=False
    )


def go_line(v1, v2, color="black", width=2, mode="lines", text=""):
    import plotly.graph_objects as go
    return go.Scatter3d(
        mode=mode,
        x=[v1[0], v2[0]],
        y=[v1[1], v2[1]],
        z=[v1[2], v2[2]],
        line=dict(color=color),
        text=text,
        showlegend=False
    )

def plot_brillouin_zone(struc, fig=None):
    bz_lattice=struc.lattice.reciprocal_lattice
    if fig is None:
        fig = go.Figure()
#   Plot the three lattice vectors        
    vertex1 = bz_lattice.get_cartesian_coords([0.0, 0.0, 0.0])
    vertex2 = bz_lattice.get_cartesian_coords([1.0, 0.0, 0.0])
    fig.add_trace(go_line(vertex1, vertex2, color="green", mode="lines+text", text=["","a"]))
    vertex2 = bz_lattice.get_cartesian_coords([0.0, 1.0, 0.0])
    fig.add_trace(go_line(vertex1, vertex2, color="green", mode="lines+text", text=["","b"]))
    vertex2 = bz_lattice.get_cartesian_coords([0.0, 0.0, 1.0])
    fig.add_trace(go_line(vertex1, vertex2, color="green", mode="lines+text", text=["","c"]))

#   Plot the Wigner-Seitz cell
    bz = bz_lattice.get_wigner_seitz_cell()
    for iface in range(len(bz)):  # pylint: disable=C0200
        for line in itertools.combinations(bz[iface], 2):
            for jface in range(len(bz)):
                if (iface < jface
                    and any(np.all(line[0] == x) for x in bz[jface])
                    and any(np.all(line[1] == x) for x in bz[jface])):
                    fig.add_trace(go_line(line[0], line[1]))

#   Plot the path in the Brillouin zone
    kpath=HighSymmKpath(struc)
    
    for line in [[kpath.kpath["kpoints"][k] for k in p] for p in kpath.kpath["path"]]:
        for k in range(1, len(line)):
            vertex1 = line[k - 1]
            vertex2 = line[k]
            vertex1 = bz_lattice.get_cartesian_coords(vertex1)
            vertex2 = bz_lattice.get_cartesian_coords(vertex2)

            fig.add_trace(go_line(vertex1, vertex2, color="red"))

    labels=kpath.kpath["kpoints"]
    vecs = []
    for point in labels.values():
        vecs.append(bz_lattice.get_cartesian_coords(point))

    fig.add_trace(go_points(vecs, color="red", labels=list(labels.keys())))

    fig.update_layout(
        scene = dict(
            xaxis = dict(visible=False, range=[-1.15,1.15],),
            yaxis = dict(visible=False, range=[-1.15,1.15],),
            zaxis = dict(visible=False, range=[-1.15,1.15],),
        )
    )
    return fig

# Dealing with the bandstructures
def get_n_branch(bs):
    return len(bs.branches)

def get_n_band(bs):
    if not "phonon" in str(type(bs)):
        return bs.bands[list(bs.bands.keys())[0]].shape[0]
    else:
        return bs.bands.shape[0]
    
def get_branch_wavevectors(bs, i_branch):
    branch = bs.branches[i_branch]
    if not "phonon" in str(type(bs)):
        start_wavevector = bs.kpoints[branch['start_index']].frac_coords
        end_wavevector = bs.kpoints[branch['end_index']].frac_coords
    else:
        start_wavevector = bs.qpoints[branch['start_index']].frac_coords
        end_wavevector = bs.qpoints[branch['end_index']].frac_coords
    return start_wavevector, end_wavevector

def get_branch_labels(bs, i_branch):
    branch = bs.branches[i_branch]
    if not "phonon" in str(type(bs)):
        start_label = bs.kpoints[branch['start_index']].label
        end_label = bs.kpoints[branch['end_index']].label
    else:
        start_label = bs.qpoints[branch['start_index']].label
        end_label = bs.qpoints[branch['end_index']].label        
    start_label = latex_fix(start_label)
    end_label = latex_fix(end_label)
    return [start_label, end_label]

def get_branch_energies(bs, i_branch, i_band):
    branch = bs.branches[i_branch]
    i_start = branch['start_index']
    i_end = branch['end_index']
    if not "phonon" in str(type(bs)):
        energies = list(bs.bands.values())[0][i_band, i_start:i_end+1]
    else:
        energies = bs.bands[i_band, i_start:i_end+1]
    return energies

def get_branch_distances(bs, i_branch):
    branch = bs.branches[i_branch]
    i_start = branch['start_index']
    i_end = branch['end_index']
    distances= bs.distance[i_start:i_end+1]-bs.distance[i_start]*np.ones(i_end-i_start+1)    
    return distances
    
def get_plot_bs(bs, branch_list = "all", plot_range = [None,None]):
    if branch_list == "all":
        branch_list = range(get_n_branch(bs))

    if not "phonon" in str(type(bs)):
        yaxis_title = "E - E<sub>f</sub> (eV)"
        yshift = bs.get_vbm()['energy']
    else:
        yaxis_title = "Frequencies (THz)"
        yshift = 0.0

    if plot_range == [None,None]:
        band_list = range(get_n_band(bs))
    else:
        band_list = []
        for i_band in range(get_n_band(bs)):
            yvals = []
            for i_branch in branch_list:
                yvals.extend(get_branch_energies(bs, i_branch, i_band) - yshift)
            if plot_range[0] == None:
                if np.min(np.array(yvals) - plot_range[1])<=0:
                    band_list.append(i_band)
            elif plot_range[1] == None:
                if np.max(np.array(yvals) - plot_range[0])>=0:
                    band_list.append(i_band)
            else:
                if np.max(np.array(yvals) - plot_range[0])>=0 and np.min(np.array(yvals) - plot_range[1])<=0:
                    band_list.append(i_band)
        
    fig = go.Figure()

    labels = []
    for i_branch in branch_list:
        new_labels = get_branch_labels(bs, i_branch)
        new_xvals = get_branch_distances(bs, i_branch)
        if len(labels) == 0:
            labels.append(new_labels[0])
            xvals = new_xvals.tolist()
            tickvals = [new_xvals[0], new_xvals[-1]]
        elif labels[-1] != new_labels[0]:
            labels[-1] += "|" + new_labels[0]
            xvals.extend((new_xvals + tickvals[-1]).tolist())
            tickvals.append(new_xvals[-1] + tickvals[-1])
        else:
            xvals.extend((new_xvals + tickvals[-1]).tolist())
            tickvals.append(new_xvals[-1] + tickvals[-1])
        labels.append(new_labels[1])
    
    for tickval in tickvals[1:-1]:
        fig.add_vline(x=tickval, line_width=1, line_color="black")

    yvals_lowest = []
    for i_branch in branch_list:
        yvals_lowest.extend(get_branch_energies(bs, i_branch, band_list[0]) - yshift)
    yvals_highest = []
    for i_branch in branch_list:
        yvals_highest.extend(get_branch_energies(bs, i_branch, band_list[-1]) - yshift)

    if plot_range == [None,None]:
        yaxis_range = [
            np.min(yvals_lowest)-0.02*abs(np.min(yvals_lowest)),
            np.max(yvals_highest)+0.02*abs(np.max(yvals_highest))]
    elif plot_range[0] == None:
        yaxis_range = [np.min(yvals_lowest)-0.02*abs(np.min(yvals_lowest)), plot_range[1]]
    elif plot_range[1] == None:
        yaxis_range = [plot_range[0], np.max(yvals_highest)+0.02*abs(np.max(yvals_highest))]
    else:
        yaxis_range = [plot_range[0], plot_range[1]]
        
    for i_band in band_list:
        yvals = []
        for i_branch in branch_list:
            yvals.extend(get_branch_energies(bs, i_branch, i_band) - yshift)
            
        scatter = go.Scatter(x=xvals, y=yvals, mode="lines", name="band "+str(i_band+1))
        fig.add_trace(scatter)
    
    fig.update_layout(
        xaxis =  {'mirror': True, 'showgrid': False,
                  'ticks': 'inside',
                  'tickvals': tickvals,
                  'ticktext': labels,
                  'ticklen':0},
        yaxis =  {'mirror': True, 'showgrid': False, 'ticks': 'inside', 'ticklen':10},
        yaxis_range = yaxis_range,
        xaxis_title = "Wave Vector",
        yaxis_title = yaxis_title
    )
    
    return fig

def get_plot_dos(dos, plot_range = [None,None]):
    fig = go.Figure()
    if not "phonon" in str(type(dos)):
        xvals = dos.energies - dos.efermi
        xaxis_title = "E - E<sub>f</sub> (eV)"
        yvals = list(dos.densities.values())[0]
    else:
        xvals = dos.frequencies
        xaxis_title = "Frequencies (THz)"
        yvals = dos.densities

    scatter = go.Scatter(x=xvals, y=yvals, mode="lines")
    fig.add_trace(scatter)
    
    if plot_range == [None, None]:
        xaxis_range = [np.min(xvals)-0.02*abs(np.min(xvals)), np.max(xvals)+0.02*abs(np.max(xvals))]
        yaxis_range = [0, 1.02*np.max(yvals)]
    elif plot_range[0] == None:
        xaxis_range = [np.min(xvals)-0.02*abs(np.min(xvals)), plot_range[1]]
        i1 = np.argmin(abs(xvals-plot_range[1]))
        yaxis_range = [0, 1.02*np.max(yvals[:i1])]
    elif plot_range[1] == None:
        xaxis_range = [plot_range[0], np.max(xvals)+0.02*abs(np.max(xvals))]
        i0 = np.argmin(abs(xvals-plot_range[0]))
        yaxis_range = [0, 1.02*np.max(yvals[i0:])]
    else: 
        xaxis_range = [plot_range[0], plot_range[1]]
        i0 = np.argmin(abs(xvals-plot_range[0]))
        i1 = np.argmin(abs(xvals-plot_range[1]))
        yaxis_range = [0, 1.02*np.max(yvals[i0:i1])]
    
    fig.update_layout(
        xaxis =  {'mirror': True, 'showgrid': False, 'ticks': 'inside', 'ticklen':10},
        yaxis =  {'mirror': True, 'showgrid': False, 'ticks': 'inside', 'ticklen':10},
        xaxis_range = xaxis_range,
        yaxis_range = yaxis_range,
        xaxis_title = xaxis_title,
        yaxis_title = "DOS",
    )
    return fig


def get_plot_bs_and_dos(bs, dos, branch_list = "all", plot_range = [None,None]):
    # Bandstructure
    if branch_list == "all":
        branch_list = range(get_n_branch(bs))

    if not "phonon" in str(type(bs)):
        yaxis_title = "E - E<sub>f</sub> (eV)"
        yshift = bs.get_vbm()['energy']
    else:
        yaxis_title = "Frequencies (THz)"
        yshift = 0.0

    if plot_range == [None,None]:
        band_list = range(get_n_band(bs))
    else:
        band_list = []
        for i_band in range(get_n_band(bs)):
            yvals = []
            for i_branch in branch_list:
                yvals.extend(get_branch_energies(bs, i_branch, i_band) - yshift)
            if plot_range[0] == None:
                if np.min(np.array(yvals) - plot_range[1])<=0:
                    band_list.append(i_band)
            elif plot_range[1] == None:
                if np.max(np.array(yvals) - plot_range[0])>=0:
                    band_list.append(i_band)
            else:
                if np.max(np.array(yvals) - plot_range[0])>=0 and np.min(np.array(yvals) - plot_range[1])<=0:
                    band_list.append(i_band)
        
    fig = make_subplots(rows=1, cols=2, shared_yaxes=True, horizontal_spacing=0.01, column_widths=[4,1])

    labels = []
    for i_branch in branch_list:
        new_labels = get_branch_labels(bs, i_branch)
        new_xvals = get_branch_distances(bs, i_branch)
        if len(labels) == 0:
            labels.append(new_labels[0])
            xvals = new_xvals.tolist()
            tickvals = [new_xvals[0], new_xvals[-1]]
        elif labels[-1] != new_labels[0]:
            labels[-1] += "|" + new_labels[0]
            xvals.extend((new_xvals + tickvals[-1]).tolist())
            tickvals.append(new_xvals[-1] + tickvals[-1])
        else:
            xvals.extend((new_xvals + tickvals[-1]).tolist())
            tickvals.append(new_xvals[-1] + tickvals[-1])
        labels.append(new_labels[1])
    
    yvals_lowest = []
    for i_branch in branch_list:
        yvals_lowest.extend(get_branch_energies(bs, i_branch, band_list[0]) - yshift)
    yvals_highest = []
    for i_branch in branch_list:
        yvals_highest.extend(get_branch_energies(bs, i_branch, band_list[-1]) - yshift)

    if plot_range == [None,None]:
        yaxis_range = [
            np.min(yvals_lowest)-0.02*abs(np.min(yvals_lowest)),
            np.max(yvals_highest)+0.02*abs(np.max(yvals_highest))]
    elif plot_range[0] == None:
        yaxis_range = [np.min(yvals_lowest)-0.02*abs(np.min(yvals_lowest)), plot_range[1]]
    elif plot_range[1] == None:
        yaxis_range = [plot_range[0], np.max(yvals_highest)+0.02*abs(np.max(yvals_highest))]
    else:
        yaxis_range = [plot_range[0], plot_range[1]]
        
    for i_band in band_list:
        yvals = []
        for i_branch in branch_list:
            yvals.extend(get_branch_energies(bs, i_branch, i_band) - yshift)
        scatter = go.Scatter(x=xvals, y=yvals, mode="lines", name="band "+str(i_band+1))
        fig.add_trace(scatter, row=1, col=1)

    for tickval in tickvals[1:-1]:
        fig.add_vline(x=tickval, line_width=1, line_color="black", row=1, col=1)
    
    # DOS
    if not "phonon" in str(type(dos)):
        xvals2 = list(dos.densities.values())[0]
        yvals2 = dos.energies - dos.efermi
    else:
        xvals2 = dos.densities
        yvals2 = dos.frequencies

    scatter = go.Scatter(x=xvals2, y=yvals2, mode="lines", showlegend=False)
    fig.add_trace(scatter, row=1, col=2)

    i0 = np.argmin(abs(yvals2-yaxis_range[0]))
    i1 = np.argmin(abs(yvals2-yaxis_range[1]))
    xaxis2_range = [0, 1.02*np.max(xvals2[i0:i1])]

    fig.update_layout(
        xaxis =  {'mirror': True, 'showgrid': False,
                  'ticks': 'inside',
                  'tickvals': tickvals,
                  'ticktext': labels,
                  'ticklen':0},
        yaxis =  {'mirror': True, 'showgrid': False, 'ticks': 'inside', 'ticklen':10},
        yaxis_range = yaxis_range,
        xaxis_title = "Wave Vector",
        yaxis_title = yaxis_title,        
        xaxis2 =  {'mirror': True, 'showgrid': False, 'ticks': 'inside', 'ticklen':10},
        yaxis2 =  {'mirror': True, 'showgrid': False, 'ticks': 'inside', 'ticklen':10},
        xaxis2_range = xaxis2_range,
        xaxis2_title = "DOS",
    )
    
    return fig

<>:9: SyntaxWarning: invalid escape sequence '\G'
<>:9: SyntaxWarning: invalid escape sequence '\G'
/var/folders/m0/79fdh5rs75s90y90257qzxg40000gn/T/ipykernel_10940/265495156.py:9: SyntaxWarning: invalid escape sequence '\G'
  "\Gamma": "Γ",


In [3]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
#from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [4]:
mp_key = "g2nCFD5rMkPRt9qdpOGhbfHJf2mgbv5x"
mp_id = "mp-14116"

In [5]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    el_bs = m.get_bandstructure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
    ph_bs = m.get_phonon_bandstructure_by_material_id(mp_id)
    ph_dos = m.get_phonon_dos_by_material_id(mp_id)
    structure = m.get_structure_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
# Visualisation
view = quick_view(structure)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [7]:
view = quick_view(prim_struc, "packed", conventional = True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [8]:
# Symétries de la molécule
sym = SpacegroupAnalyzer(structure).get_symmetry_operations()

# Symétries choisies pour les atomes
# Plan miroir (z,y,x)
S1 = sym[7]
# Axe 4-barre | centre d'inversion en (0,0,0)  (-x-y-z,x,y)
S2 = sym[3]
# Axe de rotation C2 (y,x,-x-y-z)
S3 = sym[6]

# Atomes choisis (positions fractionnaires dans CuRhO2)
Cu = [0.0, 0.0, 0.0]
Rh = [0.5, 0.5, 0.5]
O = [0.25, 0.25, 0.75]

# Application des symétries
Cu_sym = S1.operate(Cu)
Rh_sym = S2.operate(Rh)
O_sym = S3.operate(O)

# Application des oppérations de symétrie
transformed_positions = [S1.operate(Cu),
                         S2.operate(Rh),
                         S3.operate(O)]

# Affichage des résultats
print("Position originale et transformée des atomes:")
print(f"Cu: {Cu} -> {Cu_sym}")
print(f"Rh: {Rh} -> {Rh_sym}")
print(f"O: {O} -> {O_sym}")

Position originale et transformée des atomes:
Cu: [0.0, 0.0, 0.0] -> [0. 0. 0.]
Rh: [0.5, 0.5, 0.5] -> [-0.5 -0.5 -0.5]
O: [0.25, 0.25, 0.75] -> [-0.75 -0.25 -0.25]


### Première symétrie sur l'atome de Cu

In [10]:
print("Opération de symétrie 1: \n")
print("L'atome de départ est Cu et a comme coordonnées: {}\n".format(Cu))
print("On lui applique une symétrie de plan miroir (z,y,x) :\n")
print(S1.rotation_matrix, "*", Cu, '+', S1.translation_vector)
print("L'atome d'arrivée a comme coordonnées : {}\n".format(Cu_sym))

# Visualisation avec Jupyter-JSmol
v1 = quick_view(structure)
display(v1)
v1.script("draw symop 8 {atomno=1}")

Opération de symétrie 1: 

L'atome de départ est Cu et a comme coordonnées: [0.0, 0.0, 0.0]

On lui applique une symétrie de plan miroir (z,y,x) :

[[ 0.  0. -1.]
 [-1.  0.  0.]
 [ 0. -1.  0.]] * [0.0, 0.0, 0.0] + [0. 0. 0.]
L'atome d'arrivée a comme coordonnées : [0. 0. 0.]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Deuxième symétrie sur l'atome de Rh

In [12]:
print("Opération de symétrie 2: \n")
print("L'atome de départ est Rh et a comme coordonnées: {}\n".format(Rh))
print("On lui applique une roto-inversion (-x-y-z,x,y) :")
print(S2.rotation_matrix, "*", Rh, '+', S2.translation_vector)
print("L'atome d'arrivée a comme coordonnées : {}\n".format(Rh_sym))

# Visualisation avec Jupyter-JSmol
v2 = quick_view(structure)
display(v2)
v2.script("draw symop 4 {atomno=7}")

Opération de symétrie 2: 

L'atome de départ est Rh et a comme coordonnées: [0.5, 0.5, 0.5]

On lui applique une roto-inversion (-x-y-z,x,y) :
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]] * [0.5, 0.5, 0.5] + [0. 0. 0.]
L'atome d'arrivée a comme coordonnées : [-0.5 -0.5 -0.5]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Troisième symétrie sur l'atome de Ru

In [14]:
print("Opération de symétrie 3: \n")
print("L'atome de départ est le O et a comme coordonnées: {}\n".format(O))
print("On lui applique une symétrie d'axe 2 (y,x,-x-y-z) : ")
print(S3.rotation_matrix, "*", O, '+', S3.translation_vector)
print("L'atome d'arrivé a comme coordonnées : {}\n".format(O_sym))
v3 = quick_view(structure)
display(v3)
v3.script("draw symop 7 {atomno=3}")

Opération de symétrie 3: 

L'atome de départ est le O et a comme coordonnées: [0.25, 0.25, 0.75]

On lui applique une symétrie d'axe 2 (y,x,-x-y-z) : 
[[ 0.  0. -1.]
 [-1.  0.  0.]
 [ 0. -1.  0.]] * [0.25, 0.25, 0.75] + [0. 0. 0.]
L'atome d'arrivé a comme coordonnées : [-0.75 -0.25 -0.25]



JsmolView(layout=Layout(align_self='stretch', height='400px'))